version: "3.8"

services:
  psql-db:
    build: ./
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis-db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /data:/root/redis
      - /data/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=qwerty
      - REDIS_PORT=6379
      - REDIS_DATABASES=0
